/**
 * Auto-generated execution implementation for bdev ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/bdev/bdev_runtime.h"
#include "chimaera/bdev/autogen/bdev_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace chimaera::bdev {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      co_await Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      co_await Destroy(typed_task, rctx);
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      co_await Monitor(typed_task, rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<AllocateBlocksTask> typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      co_await AllocateBlocks(typed_task, rctx);
      break;
    }
    case Method::kFreeBlocks: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<FreeBlocksTask> typed_task = task_ptr.template Cast<FreeBlocksTask>();
      co_await FreeBlocks(typed_task, rctx);
      break;
    }
    case Method::kWrite: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<WriteTask> typed_task = task_ptr.template Cast<WriteTask>();
      co_await Write(typed_task, rctx);
      break;
    }
    case Method::kRead: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ReadTask> typed_task = task_ptr.template Cast<ReadTask>();
      co_await Read(typed_task, rctx);
      break;
    }
    case Method::kGetStats: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetStatsTask> typed_task = task_ptr.template Cast<GetStatsTask>();
      co_await GetStats(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  // co_return makes this a coroutine returning TaskResume
  co_return;
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAllocateBlocks: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<AllocateBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFreeBlocks: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FreeBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWrite: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<WriteTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRead: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ReadTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetStats: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetStatsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAllocateBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFreeBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kWrite: {
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRead: {
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetStats: {
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> orig_task,
                        const hipc::FullPtr<chi::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = orig_task.template Cast<AllocateBlocksTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = orig_task.template Cast<FreeBlocksTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kWrite: {
      auto typed_task = orig_task.template Cast<WriteTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRead: {
      auto typed_task = orig_task.template Cast<ReadTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetStats: {
      auto typed_task = orig_task.template Cast<GetStatsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    default: {
      orig_task->Aggregate(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kAllocateBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<AllocateBlocksTask>());
      break;
    }
    case Method::kFreeBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<FreeBlocksTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.template Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.template Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.template Cast<GetStatsTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace chimaera::bdev
