/**
 * Auto-generated execution implementation for bdev ChiMod
 * Implements Container virtual APIs (Run, DelTask, SaveTask, LoadTask, NewCopyTask, NewTask, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/bdev/bdev_runtime.h"
#include "chimaera/bdev/autogen/bdev_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace chimaera::bdev {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<AllocateBlocksTask> typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      AllocateBlocks(typed_task, rctx);
      break;
    }
    case Method::kFreeBlocks: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<FreeBlocksTask> typed_task = task_ptr.template Cast<FreeBlocksTask>();
      FreeBlocks(typed_task, rctx);
      break;
    }
    case Method::kWrite: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<WriteTask> typed_task = task_ptr.template Cast<WriteTask>();
      Write(typed_task, rctx);
      break;
    }
    case Method::kRead: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ReadTask> typed_task = task_ptr.template Cast<ReadTask>();
      Read(typed_task, rctx);
      break;
    }
    case Method::kGetStats: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetStatsTask> typed_task = task_ptr.template Cast<GetStatsTask>();
      GetStats(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  // co_return makes this a coroutine returning TaskResume
  co_return;
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kAllocateBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<AllocateBlocksTask>());
      break;
    }
    case Method::kFreeBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<FreeBlocksTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.template Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.template Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.template Cast<GetStatsTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAllocateBlocks: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<AllocateBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFreeBlocks: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FreeBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWrite: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<WriteTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRead: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ReadTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetStats: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetStatsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAllocateBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFreeBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kWrite: {
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRead: {
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetStats: {
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> origin_task_ptr,
                         hipc::FullPtr<chi::Task> replica_task_ptr) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<CreateTask>();
      auto typed_replica = replica_task_ptr.template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DestroyTask>();
      auto typed_replica = replica_task_ptr.template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kAllocateBlocks: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<AllocateBlocksTask>();
      auto typed_replica = replica_task_ptr.template Cast<AllocateBlocksTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kFreeBlocks: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<FreeBlocksTask>();
      auto typed_replica = replica_task_ptr.template Cast<FreeBlocksTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kWrite: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<WriteTask>();
      auto typed_replica = replica_task_ptr.template Cast<WriteTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kRead: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<ReadTask>();
      auto typed_replica = replica_task_ptr.template Cast<ReadTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetStats: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetStatsTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetStatsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_task_ptr.ptr_->Aggregate(replica_task_ptr);
      break;
    }
  }
}

} // namespace chimaera::bdev
