/**
 * Auto-generated execution implementation for coeus_mdm ChiMod
 * Implements Container virtual APIs (Run, DelTask, SaveTask, LoadTask, NewCopyTask, NewTask, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "../include/chimaera/coeus_mdm/coeus_mdm_runtime.h"
#include "../include/chimaera/coeus_mdm/autogen/coeus_mdm_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace chimaera::coeus_mdm {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_.Init(pool_id);
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kMdm_insert: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<Mdm_insertTask> typed_task = task_ptr.template Cast<Mdm_insertTask>();
      Mdm_insert(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  // co_return makes this a coroutine returning TaskResume
  co_return;
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMdm_insert: {
      ipc_manager->DelTask(task_ptr.template Cast<Mdm_insertTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMdm_insert: {
      auto typed_task = task_ptr.template Cast<Mdm_insertTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMdm_insert: {
      auto typed_task = task_ptr.template Cast<Mdm_insertTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kMdm_insert: {
      auto typed_task = task_ptr.template Cast<Mdm_insertTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kMdm_insert: {
      auto typed_task = task_ptr.template Cast<Mdm_insertTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        new_task_ptr->Copy(orig_task_ptr.template Cast<CreateTask>());
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr.template Cast<DestroyTask>());
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMdm_insert: {
      auto new_task_ptr = ipc_manager->NewTask<Mdm_insertTask>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr.template Cast<Mdm_insertTask>());
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
  }
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMdm_insert: {
      auto new_task_ptr = ipc_manager->NewTask<Mdm_insertTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> origin_task_ptr,
                         hipc::FullPtr<chi::Task> replica_task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto origin_task = origin_task_ptr.template Cast<CreateTask>();
      auto replica_task = replica_task_ptr.template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      origin_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto origin_task = origin_task_ptr.template Cast<DestroyTask>();
      auto replica_task = replica_task_ptr.template Cast<DestroyTask>();
      origin_task->Aggregate(replica_task);
      break;
    }
    case Method::kMdm_insert: {
      auto origin_task = origin_task_ptr.template Cast<Mdm_insertTask>();
      auto replica_task = replica_task_ptr.template Cast<Mdm_insertTask>();
      origin_task->Aggregate(replica_task);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_task_ptr->Aggregate(replica_task_ptr);
      break;
    }
  }
}

}  // namespace chimaera::coeus_mdm

