
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/lukemartinlogan/.local/programs/clion-2021.3.2/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.4.0-162-generic - x86_64
...
