/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs (Run, DelTask, SaveTask, LoadTask, NewCopyTask, NewTask, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/admin/admin_runtime.h"
#include "chimaera/admin/autogen/admin_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace chimaera::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      co_await Destroy(typed_task, rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<admin::GetOrCreatePoolTask<admin::CreateParams>> typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      co_await GetOrCreatePool(typed_task, rctx);
      break;
    }
    case Method::kDestroyPool: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyPoolTask> typed_task = task_ptr.template Cast<DestroyPoolTask>();
      co_await DestroyPool(typed_task, rctx);
      break;
    }
    case Method::kStopRuntime: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<StopRuntimeTask> typed_task = task_ptr.template Cast<StopRuntimeTask>();
      StopRuntime(typed_task, rctx);
      break;
    }
    case Method::kFlush: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<FlushTask> typed_task = task_ptr.template Cast<FlushTask>();
      Flush(typed_task, rctx);
      break;
    }
    case Method::kSend: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<SendTask> typed_task = task_ptr.template Cast<SendTask>();
      Send(typed_task, rctx);
      break;
    }
    case Method::kRecv: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RecvTask> typed_task = task_ptr.template Cast<RecvTask>();
      Recv(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  // co_return makes this a coroutine returning TaskResume
  co_return;
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kGetOrCreatePool: {
      ipc_manager->DelTask(task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
      break;
    }
    case Method::kDestroyPool: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyPoolTask>());
      break;
    }
    case Method::kStopRuntime: {
      ipc_manager->DelTask(task_ptr.template Cast<StopRuntimeTask>());
      break;
    }
    case Method::kFlush: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushTask>());
      break;
    }
    case Method::kSend: {
      ipc_manager->DelTask(task_ptr.template Cast<SendTask>());
      break;
    }
    case Method::kRecv: {
      ipc_manager->DelTask(task_ptr.template Cast<RecvTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyPoolTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<StopRuntimeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FlushTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSend: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<SendTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRecv: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RecvTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetOrCreatePool: {
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroyPool: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kStopRuntime: {
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFlush: {
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSend: {
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRecv: {
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> origin_task_ptr,
                         hipc::FullPtr<chi::Task> replica_task_ptr) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<CreateTask>();
      auto typed_replica = replica_task_ptr.template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DestroyTask>();
      auto typed_replica = replica_task_ptr.template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetOrCreatePool: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      auto typed_replica = replica_task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroyPool: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DestroyPoolTask>();
      auto typed_replica = replica_task_ptr.template Cast<DestroyPoolTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kStopRuntime: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<StopRuntimeTask>();
      auto typed_replica = replica_task_ptr.template Cast<StopRuntimeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kFlush: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<FlushTask>();
      auto typed_replica = replica_task_ptr.template Cast<FlushTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kSend: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<SendTask>();
      auto typed_replica = replica_task_ptr.template Cast<SendTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kRecv: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<RecvTask>();
      auto typed_replica = replica_task_ptr.template Cast<RecvTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_task_ptr.ptr_->Aggregate(replica_task_ptr);
      break;
    }
  }
}

} // namespace chimaera::admin
