/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, DelTask, SaveTask, LoadTask, NewCopyTask, NewTask, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "wrp_cte/core/core_runtime.h"
#include "wrp_cte/core/autogen/core_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace wrp_cte::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      co_await Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kRegisterTarget: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RegisterTargetTask> typed_task = task_ptr.template Cast<RegisterTargetTask>();
      co_await RegisterTarget(typed_task, rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<UnregisterTargetTask> typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      UnregisterTarget(typed_task, rctx);
      break;
    }
    case Method::kListTargets: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ListTargetsTask> typed_task = task_ptr.template Cast<ListTargetsTask>();
      ListTargets(typed_task, rctx);
      break;
    }
    case Method::kStatTargets: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<StatTargetsTask> typed_task = task_ptr.template Cast<StatTargetsTask>();
      StatTargets(typed_task, rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<core::GetOrCreateTagTask<core::CreateParams>> typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      GetOrCreateTag(typed_task, rctx);
      break;
    }
    case Method::kPutBlob: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<PutBlobTask> typed_task = task_ptr.template Cast<PutBlobTask>();
      co_await PutBlob(typed_task, rctx);
      break;
    }
    case Method::kGetBlob: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetBlobTask> typed_task = task_ptr.template Cast<GetBlobTask>();
      co_await GetBlob(typed_task, rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ReorganizeBlobTask> typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      co_await ReorganizeBlob(typed_task, rctx);
      break;
    }
    case Method::kDelBlob: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DelBlobTask> typed_task = task_ptr.template Cast<DelBlobTask>();
      co_await DelBlob(typed_task, rctx);
      break;
    }
    case Method::kDelTag: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DelTagTask> typed_task = task_ptr.template Cast<DelTagTask>();
      co_await DelTag(typed_task, rctx);
      break;
    }
    case Method::kGetTagSize: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetTagSizeTask> typed_task = task_ptr.template Cast<GetTagSizeTask>();
      GetTagSize(typed_task, rctx);
      break;
    }
    case Method::kPollTelemetryLog: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<PollTelemetryLogTask> typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      PollTelemetryLog(typed_task, rctx);
      break;
    }
    case Method::kGetBlobScore: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetBlobScoreTask> typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      GetBlobScore(typed_task, rctx);
      break;
    }
    case Method::kGetBlobSize: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetBlobSizeTask> typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      GetBlobSize(typed_task, rctx);
      break;
    }
    case Method::kGetContainedBlobs: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<GetContainedBlobsTask> typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      GetContainedBlobs(typed_task, rctx);
      break;
    }
    case Method::kTagQuery: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<TagQueryTask> typed_task = task_ptr.template Cast<TagQueryTask>();
      TagQuery(typed_task, rctx);
      break;
    }
    case Method::kBlobQuery: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<BlobQueryTask> typed_task = task_ptr.template Cast<BlobQueryTask>();
      BlobQuery(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  // co_return makes this a coroutine returning TaskResume
  co_return;
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<ListTargetsTask>());
      break;
    }
    case Method::kStatTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<StatTargetsTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobTask>());
      break;
    }
    case Method::kReorganizeBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<ReorganizeBlobTask>());
      break;
    }
    case Method::kDelBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<DelBlobTask>());
      break;
    }
    case Method::kDelTag: {
      ipc_manager->DelTask(task_ptr.template Cast<DelTagTask>());
      break;
    }
    case Method::kGetTagSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetTagSizeTask>());
      break;
    }
    case Method::kPollTelemetryLog: {
      ipc_manager->DelTask(task_ptr.template Cast<PollTelemetryLogTask>());
      break;
    }
    case Method::kGetBlobScore: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobScoreTask>());
      break;
    }
    case Method::kGetBlobSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobSizeTask>());
      break;
    }
    case Method::kGetContainedBlobs: {
      ipc_manager->DelTask(task_ptr.template Cast<GetContainedBlobsTask>());
      break;
    }
    case Method::kTagQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<TagQueryTask>());
      break;
    }
    case Method::kBlobQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<BlobQueryTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Call SerializeIn - task will call Task::SerializeIn for base fields
      typed_task.ptr_->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::LocalLoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Call SerializeOut - task will call Task::SerializeOut for base fields
      typed_task.ptr_->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RegisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<UnregisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kListTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ListTargetsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStatTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<StatTargetsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<PutBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ReorganizeBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDelBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DelBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDelTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DelTagTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetTagSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetTagSizeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<PollTelemetryLogTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobScoreTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobSizeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetContainedBlobsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kTagQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<TagQueryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kBlobQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<BlobQueryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRegisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kUnregisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kListTargets: {
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kStatTargets: {
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kReorganizeBlob: {
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDelBlob: {
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDelTag: {
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetTagSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kPollTelemetryLog: {
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlobScore: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlobSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetContainedBlobs: {
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kTagQuery: {
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kBlobQuery: {
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> origin_task_ptr,
                         hipc::FullPtr<chi::Task> replica_task_ptr) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<CreateTask>();
      auto typed_replica = replica_task_ptr.template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DestroyTask>();
      auto typed_replica = replica_task_ptr.template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kRegisterTarget: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<RegisterTargetTask>();
      auto typed_replica = replica_task_ptr.template Cast<RegisterTargetTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kUnregisterTarget: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<UnregisterTargetTask>();
      auto typed_replica = replica_task_ptr.template Cast<UnregisterTargetTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kListTargets: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<ListTargetsTask>();
      auto typed_replica = replica_task_ptr.template Cast<ListTargetsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kStatTargets: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<StatTargetsTask>();
      auto typed_replica = replica_task_ptr.template Cast<StatTargetsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetOrCreateTag: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      auto typed_replica = replica_task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kPutBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<PutBlobTask>();
      auto typed_replica = replica_task_ptr.template Cast<PutBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetBlobTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kReorganizeBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<ReorganizeBlobTask>();
      auto typed_replica = replica_task_ptr.template Cast<ReorganizeBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDelBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DelBlobTask>();
      auto typed_replica = replica_task_ptr.template Cast<DelBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kDelTag: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<DelTagTask>();
      auto typed_replica = replica_task_ptr.template Cast<DelTagTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetTagSize: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetTagSizeTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetTagSizeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kPollTelemetryLog: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<PollTelemetryLogTask>();
      auto typed_replica = replica_task_ptr.template Cast<PollTelemetryLogTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlobScore: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetBlobScoreTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetBlobScoreTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlobSize: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetBlobSizeTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetBlobSizeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kGetContainedBlobs: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<GetContainedBlobsTask>();
      auto typed_replica = replica_task_ptr.template Cast<GetContainedBlobsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kTagQuery: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<TagQueryTask>();
      auto typed_replica = replica_task_ptr.template Cast<TagQueryTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    case Method::kBlobQuery: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_task_ptr.template Cast<BlobQueryTask>();
      auto typed_replica = replica_task_ptr.template Cast<BlobQueryTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin.ptr_->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_task_ptr.ptr_->Aggregate(replica_task_ptr);
      break;
    }
  }
}

} // namespace wrp_cte::core
